export enum Category {
    TECHNOLOGY = "TECHNOLOGY",
    CLOTHING = "CLOTHING",
    FOOD = "FOOD",
    FURNITURE = "FURNITURE",
    TOYS = "TOYS",
    BOOKS = "BOOKS",
    GAMES = "GAMES",
    ELECTRONICS = "ELECTRONICS",
    JEWELERY = "JEWELERY",
}